name: MobPlugin
main: net.twoptwoe.mobplugin.MobPlugin
version: "1.0"
api: ["1.0.0"]

load: STARTUP
author: kniffo80, matt404, augesrob, PetteriM1, PikyCZ
description: Mob plugin for Nukkit
website: https://github.com/Nukkit-coders/mob-plugin

commands:
  mob:
    description: MobPlugin main command
    aliases: ["mob"]
    usage: /mob
    permission: mobplugin.command  
    
permissions:
  novamobs.mob:
    description: ""
    default: op
